"""
gerber — RS-274X (Gerber X1) 写出器

Reference: Ucamco《The Gerber Format Specification》Revision 2024.05
本实现覆盖最常用子集, 与主流制造商兼容:
    - 单位 / 格式声明: %MOMM*% , %FSLAX46Y46*%
    - 光圈定义: %ADDxx<C|R|O|P>,...*%
    - 操作: D01 (draw line), D02 (move), D03 (flash), G01 (linear)
    - 旋转: rectangular pads only — 90°/180°/270° 用 swap+mirror, 任意角度暂不支持
    - 注释: G04 ...*

每层一份文件:
    F.Cu     → <project>-F_Cu.gbr
    B.Cu     → <project>-B_Cu.gbr
    F.SilkS  → <project>-F_SilkS.gbr
    B.SilkS  → <project>-B_SilkS.gbr
    F.Mask   → <project>-F_Mask.gbr
    B.Mask   → <project>-B_Mask.gbr
    Edge.Cuts → <project>-Edge_Cuts.gbr

用法:
    >>> from kicad_origin.engine.gerber import write_gerber
    >>> from kicad_origin import Board
    >>> b = Board.load("project.kicad_pcb")
    >>> files = write_gerber(b, output_dir="./fab")
    >>> print(files)  # ['./fab/project-F_Cu.gbr', ...]
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

from kicad_origin.origin.sexpr import find_all, find_first
from kicad_origin.pcb.board import Board
from kicad_origin.pcb.footprint import Footprint
from kicad_origin.pcb.pad import Pad


# ─────────────────────────────────────────────────────────────────────
# 标准制造层 (KiCad 名 → Gerber 后缀)
# ─────────────────────────────────────────────────────────────────────
GERBER_LAYERS: Dict[str, str] = {
    "F.Cu":      "F_Cu",
    "B.Cu":      "B_Cu",
    "F.SilkS":   "F_SilkS",
    "B.SilkS":   "B_SilkS",
    "F.Mask":    "F_Mask",
    "B.Mask":    "B_Mask",
    "F.Paste":   "F_Paste",
    "B.Paste":   "B_Paste",
    "F.Fab":     "F_Fab",
    "B.Fab":     "B_Fab",
    "Edge.Cuts": "Edge_Cuts",
}


# ─────────────────────────────────────────────────────────────────────
# 写出器
# ─────────────────────────────────────────────────────────────────────
class GerberWriter:
    """单层 Gerber 文件写出器. 自动光圈分配."""

    # 数值格式: 4 位整数, 6 位小数 (Gerber X1 标准, 单位 mm)
    INT_DIGITS  = 4
    DEC_DIGITS  = 6

    def __init__(self, layer: str):
        self.layer = layer
        self.lines: List[str] = []
        # 光圈表: aperture_def_str → D-code (从 D10 开始)
        self.apertures: Dict[str, int] = {}
        self.next_d = 10
        self._write_header()

    # ── 头/尾 ────────────────────────────────────────────────────
    def _write_header(self) -> None:
        self.lines.append(f"G04 Layer {self.layer} generated by kicad_origin*")
        self.lines.append("%FSLAX46Y46*%")  # leading-zero suppress, abs, 4.6 fmt
        self.lines.append("%MOMM*%")        # millimeters
        self.lines.append("%LPD*%")         # polarity dark (additive)
        self.lines.append("G01*")           # linear interpolation

    def _write_footer(self) -> None:
        self.lines.append("M02*")

    # ── 光圈 ────────────────────────────────────────────────────
    def _ap_circle(self, dia: float) -> int:
        key = f"C,{dia:.6f}"
        return self._get_or_alloc(key)

    def _ap_rect(self, w: float, h: float) -> int:
        key = f"R,{w:.6f}X{h:.6f}"
        return self._get_or_alloc(key)

    def _ap_oval(self, w: float, h: float) -> int:
        key = f"O,{w:.6f}X{h:.6f}"
        return self._get_or_alloc(key)

    def _get_or_alloc(self, key: str) -> int:
        if key in self.apertures:
            return self.apertures[key]
        d = self.next_d
        self.next_d += 1
        self.apertures[key] = d
        return d

    def _emit_apertures(self) -> List[str]:
        """生成 %ADD... 行 (按 D-code 升序)."""
        out: List[str] = []
        for key, d in sorted(self.apertures.items(), key=lambda kv: kv[1]):
            out.append(f"%ADD{d}{key}*%")
        return out

    # ── 坐标编码 ────────────────────────────────────────────────
    def _coord(self, mm: float) -> int:
        """mm → Gerber 4.6 整数 (suppress leading zeros)."""
        return int(round(mm * (10 ** self.DEC_DIGITS)))

    def _xy(self, x: float, y: float) -> str:
        # KiCad y 向下, Gerber y 向上 → 翻转 y
        ix = self._coord(x)
        iy = self._coord(-y)
        return f"X{ix}Y{iy}"

    # ── 绘制原语 ────────────────────────────────────────────────
    def flash(self, x: float, y: float, d_code: int) -> None:
        """D03 在 (x,y) 闪光 (绘制焊盘)."""
        self.lines.append(f"D{d_code}*")
        self.lines.append(f"{self._xy(x, y)}D03*")

    def draw_line(self, x1: float, y1: float, x2: float, y2: float,
                  d_code: int) -> None:
        """D01 从 (x1,y1) 画到 (x2,y2)."""
        self.lines.append(f"D{d_code}*")
        self.lines.append(f"{self._xy(x1, y1)}D02*")  # move-to
        self.lines.append(f"{self._xy(x2, y2)}D01*")  # draw-to

    # ── 高层 ────────────────────────────────────────────────────
    def add_pad(self, abs_x: float, abs_y: float, pad: Pad) -> None:
        """绘制焊盘. 当前仅支持 0/90/180/270° 旋转."""
        w, h = pad.width, pad.height
        if w <= 0 or h <= 0:
            return
        rot = int(round(pad.rotation)) % 180
        if rot == 90:
            w, h = h, w  # 矩形/椭圆 90° = 长宽互换
        shape = pad.shape
        if shape == "circle":
            d = self._ap_circle(w)  # 圆只用宽
        elif shape == "rect" or shape == "roundrect":
            d = self._ap_rect(w, h)
        elif shape == "oval":
            d = self._ap_oval(w, h)
        else:
            # 自定义形状降级为外接矩形
            d = self._ap_rect(w, h)
        self.flash(abs_x, abs_y, d)

    def add_segment(self, x1: float, y1: float, x2: float, y2: float,
                    width: float) -> None:
        """绘制走线段."""
        d = self._ap_circle(width)
        self.draw_line(x1, y1, x2, y2, d)

    # ── 终结 ────────────────────────────────────────────────────
    def finalize(self) -> str:
        self._write_footer()
        # 在头部 (G01* 之后, 第一个绘制之前) 插入光圈定义
        # 找到 "G01*" 行号
        out = []
        inserted = False
        for ln in self.lines:
            out.append(ln)
            if not inserted and ln == "G01*":
                out.extend(self._emit_apertures())
                inserted = True
        if not inserted:
            # G01 不存在? 退化为追加到末尾前
            out = self._emit_apertures() + out
        return "\n".join(out) + "\n"


# ─────────────────────────────────────────────────────────────────────
# 顶层: 一次写出全部层
# ─────────────────────────────────────────────────────────────────────
def write_gerber(board: Board, output_dir: Union[str, Path],
                 *, project_name: Optional[str] = None,
                 layers: Optional[List[str]] = None) -> List[str]:
    """把 Board 写成 Gerber 文件群. 返回写出的文件路径列表.

    Args:
        board: kicad_origin.Board
        output_dir: 输出目录, 自动创建
        project_name: 默认从 board.path 推断, fallback 为 'project'
        layers: 指定要写的层名 (KiCad 名), 默认全部 GERBER_LAYERS
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if project_name is None:
        if board.path:
            project_name = Path(board.path).stem
        else:
            project_name = board.title or "project"

    target_layers = layers if layers else list(GERBER_LAYERS.keys())

    # 为每层准备一个 writer
    writers: Dict[str, GerberWriter] = {
        L: GerberWriter(L) for L in target_layers
    }

    # ── 焊盘 ────────────────────────────────────────────────────
    for fp in board.footprints():
        center = fp.position
        fp_layer = fp.layer  # F.Cu 或 B.Cu
        fp_back = fp.is_back_side
        for pad in fp.pads():
            pp = pad.position
            ax = center.x + pp.x
            ay = center.y + pp.y
            # 焊盘可能贯穿 (thru_hole) 或单层 (smd)
            for L in pad.layers:
                # 通配符展开
                expanded = _expand_layer(L, fp_back)
                for actual in expanded:
                    if actual in writers:
                        writers[actual].add_pad(ax, ay, pad)

    # ── 走线 segment → F.Cu / B.Cu / 内层 ────────────────────────
    for seg in board.segments():
        if seg.layer in writers:
            s, e = seg.start, seg.end
            writers[seg.layer].add_segment(s.x, s.y, e.x, e.y, seg.width)

    # ── 过孔 via → F.Cu + B.Cu (贯穿) ─────────────────────────────
    for via in board.vias():
        ap_size = via.size
        for L in via.layers:
            if L in writers:
                writers[L].add_pad_circle(via.position.x, via.position.y, ap_size) \
                    if hasattr(writers[L], "add_pad_circle") else _flash_circle(
                        writers[L], via.position.x, via.position.y, ap_size)

    # ── Edge.Cuts: gr_rect / gr_line / gr_arc ────────────────────
    if "Edge.Cuts" in writers:
        edge = writers["Edge.Cuts"]
        # gr_rect
        for r in find_all(board.tree, "gr_rect"):
            ly = find_first(r, "layer")
            if not ly or len(ly) < 2 or ly[1] != "Edge.Cuts":
                continue
            st = find_first(r, "start")
            en = find_first(r, "end")
            stroke = find_first(r, "stroke")
            w = 0.1
            if stroke:
                wn = find_first(stroke, "width")
                if wn and len(wn) >= 2:
                    try: w = float(wn[1])
                    except Exception: pass
            if st and en and len(st) >= 3 and len(en) >= 3:
                x1, y1 = float(st[1]), float(st[2])
                x2, y2 = float(en[1]), float(en[2])
                # 矩形 4 段
                edge.add_segment(x1, y1, x2, y1, w)
                edge.add_segment(x2, y1, x2, y2, w)
                edge.add_segment(x2, y2, x1, y2, w)
                edge.add_segment(x1, y2, x1, y1, w)
        # gr_line
        for ln in find_all(board.tree, "gr_line"):
            ly = find_first(ln, "layer")
            if not ly or len(ly) < 2 or ly[1] != "Edge.Cuts":
                continue
            st = find_first(ln, "start")
            en = find_first(ln, "end")
            stroke = find_first(ln, "stroke")
            w = 0.1
            if stroke:
                wn = find_first(stroke, "width")
                if wn and len(wn) >= 2:
                    try: w = float(wn[1])
                    except Exception: pass
            if st and en and len(st) >= 3 and len(en) >= 3:
                edge.add_segment(float(st[1]), float(st[2]),
                                 float(en[1]), float(en[2]), w)

    # ── 写出 ────────────────────────────────────────────────────
    out_paths: List[str] = []
    for L, writer in writers.items():
        suffix = GERBER_LAYERS[L]
        path = out_dir / f"{project_name}-{suffix}.gbr"
        path.write_text(writer.finalize(), encoding="utf-8")
        out_paths.append(str(path))
    return sorted(out_paths)


# ─────────────────────────────────────────────────────────────────────
# 辅助
# ─────────────────────────────────────────────────────────────────────
def _expand_layer(layer: str, footprint_on_back: bool) -> List[str]:
    """把 pad 的 layer 通配符展开. 若 footprint 在 B 面, 自动翻转 F↔B."""
    if layer == "*.Cu":
        return ["F.Cu", "B.Cu"]
    if layer == "*.Mask":
        return ["F.Mask", "B.Mask"]
    if layer == "*.Paste":
        return ["F.Paste", "B.Paste"]
    if layer == "*.SilkS":
        return ["F.SilkS", "B.SilkS"]
    if layer == "*.Fab":
        return ["F.Fab", "B.Fab"]
    if footprint_on_back and layer.startswith("F."):
        return ["B." + layer[2:]]
    if footprint_on_back and layer.startswith("B."):
        return ["F." + layer[2:]]
    return [layer]


def _flash_circle(writer: GerberWriter, x: float, y: float, dia: float) -> None:
    """绕过 add_pad — 直接 flash 一个圆."""
    d = writer._ap_circle(dia)
    writer.flash(x, y, d)


# ─────────────────────────────────────────────────────────────────────
# 自检
# ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys
    import tempfile
    if len(sys.argv) > 1:
        b = Board.load(sys.argv[1])
        out = sys.argv[2] if len(sys.argv) > 2 else tempfile.mkdtemp(prefix="gbr_")
        files = write_gerber(b, out)
        for f in files:
            sz = Path(f).stat().st_size
            print(f"{sz:>8} bytes  {f}")
    else:
        # 自检: 空板写出 11 层 Gerber
        b = Board.empty(width_mm=50, height_mm=40)
        with tempfile.TemporaryDirectory() as d:
            files = write_gerber(b, d)
            print(f"empty board → {len(files)} layers")
            for f in files:
                head = Path(f).read_text(encoding="utf-8").splitlines()[:6]
                print(f"  {Path(f).name}: {head[0][:40]}...")
        print("gerber.py 自检 ✅")
